# coding: utf-8

"""
    Owen's Geocoding API

    An API for caching geocoding locations as fetched from Nominatim.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geocoding_nominatim_cache_client_python.models.main_error_response import MainErrorResponse

class TestMainErrorResponse(unittest.TestCase):
    """MainErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MainErrorResponse:
        """Test MainErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MainErrorResponse`
        """
        model = MainErrorResponse()
        if include_optional:
            return MainErrorResponse(
                error = 'invalid input'
            )
        else:
            return MainErrorResponse(
        )
        """

    def testMainErrorResponse(self):
        """Test MainErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
