# coding: utf-8

"""
    Owen's Geocoding API

    An API for caching geocoding locations as fetched from Nominatim.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geocoding_nominatim_cache_client_python.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_locations_place_get(self) -> None:
        """Test case for locations_place_get

        Get location coordinates for a placename
        """
        pass


if __name__ == '__main__':
    unittest.main()
