# coding: utf-8

# flake8: noqa
"""
    Owen's Geocoding API

    An API for caching geocoding locations as fetched from Nominatim.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from geocoding_nominatim_cache_client_python.models.location_location import LocationLocation
from geocoding_nominatim_cache_client_python.models.main_error_response import MainErrorResponse
